/**
 * Realistic position generation.
 *
 * The first version put two or three pieces on an empty board and asked which
 * knight could reach a square. With only one knight visible the answer was
 * never in doubt, so the exercise trained nothing.
 *
 * Positions here are produced by playing random *legal* moves from the normal
 * starting position, which guarantees by construction that they are reachable,
 * legal, and have the piece density of a real game. Nothing is hand-written,
 * and every position is validated by chess.js before it is used.
 */

import { Chess } from 'chess.js';
import { STARTING_FEN } from './position';
import type { PieceColor, PieceType, SquareName } from './types';
import type { Rng } from '../rng';

/** Piece-count window that reads as a real game rather than an endgame study. */
export const MIN_PIECES = 10;
export const MAX_PIECES = 26;

export interface PositionRequest {
  /** Side whose move the exercise is about. */
  turn?: PieceColor;
  /** Minimum and maximum total pieces on the board. */
  minPieces?: number;
  maxPieces?: number;
  /** How many plies to play out. More plies means fewer pieces. */
  minPlies?: number;
  maxPlies?: number;
  /** Reject positions where the side to move is in check. */
  avoidCheck?: boolean;
  /** The position must contain at least this many of the given piece. */
  require?: { type: PieceType; color: PieceColor; count: number };
}

export interface GeneratedPosition {
  fen: string;
  /** Total pieces on the board. */
  pieceCount: number;
  /** Plies played from the starting position. */
  plies: number;
}

function pieceCountOf(chess: Chess): number {
  return chess
    .board()
    .flat()
    .filter((square) => square !== null).length;
}

function countPiece(chess: Chess, type: PieceType, color: PieceColor): number {
  const symbol = type === 'knight' ? 'n' : type[0];
  return chess
    .board()
    .flat()
    .filter((square) => square !== null && square.type === symbol && square.color === color[0])
    .length;
}

/**
 * Plays random legal moves from the start and returns the position if it meets
 * the request. Returns null when it does not, so the caller can retry with a
 * different seed rather than being handed something unsuitable.
 */
function attemptPosition(rng: Rng, request: PositionRequest): GeneratedPosition | null {
  const { turn, minPieces = MIN_PIECES, maxPieces = MAX_PIECES, avoidCheck = true, require } = request;

  /*
   * The ply window has to stay wide even when specific pieces are required.
   * Shortening it looks like it should help - knights survive a short game -
   * but a short game also still has 30+ pieces, which fails the density
   * window. Reaching 26 pieces or fewer takes six captures, so the position
   * has to come from a mid-length game where the captures happened to fall
   * elsewhere. That is a rejection-sampling problem, not a range problem.
   */
  const minPlies = request.minPlies ?? 8;
  const maxPlies = request.maxPlies ?? 50;

  const chess = new Chess(STARTING_FEN);
  const plies = rng.nextIntBetween(minPlies, maxPlies);

  for (let i = 0; i < plies; i += 1) {
    const moves = chess.moves();
    if (moves.length === 0) break; // Checkmate or stalemate.
    chess.move(rng.pick(moves));
  }

  // Play one more ply if the wrong side is to move.
  if (turn !== undefined && chess.turn() !== turn[0]) {
    const moves = chess.moves();
    if (moves.length === 0) return null;
    chess.move(rng.pick(moves));
  }

  if (chess.isGameOver()) return null;
  if (avoidCheck && chess.isCheck()) return null;

  const count = pieceCountOf(chess);
  if (count < minPieces || count > maxPieces) return null;

  if (require !== undefined && countPiece(chess, require.type, require.color) < require.count) {
    return null;
  }

  return { fen: chess.fen(), pieceCount: count, plies };
}

/**
 * Generates a position meeting the request, retrying until it finds one.
 *
 * Returns null after `attempts` tries rather than looping forever; callers
 * fall back to a simpler position so a session can never hang.
 */
export function generatePosition(
  rng: Rng,
  request: PositionRequest = {},
  attempts = 200,
): GeneratedPosition | null {
  for (let i = 0; i < attempts; i += 1) {
    const position = attemptPosition(rng, request);
    if (position !== null) return position;
  }
  return null;
}

export interface MoveOption {
  /** Standard algebraic notation, generated by chess.js - never hand-built. */
  san: string;
  from: SquareName;
  to: SquareName;
  type: PieceType;
  /** Other pieces of the same type and colour that could also reach `to`. */
  rivals: SquareName[];
  /** True when SAN needed a file or rank to disambiguate. */
  isDisambiguated: boolean;
}

const SYMBOL_TO_TYPE: Record<string, PieceType> = {
  p: 'pawn',
  n: 'knight',
  b: 'bishop',
  r: 'rook',
  q: 'queen',
  k: 'king',
};

/**
 * Every legal move in a position, annotated with the information a notation
 * exercise needs: which same-type pieces compete for the destination, and
 * whether SAN had to disambiguate.
 */
export function describeMoves(fen: string): MoveOption[] {
  let chess: Chess;
  try {
    chess = new Chess(fen);
  } catch {
    return [];
  }

  const verbose = chess.moves({ verbose: true });

  return verbose.map((move) => {
    const type = SYMBOL_TO_TYPE[move.piece] as PieceType;
    const rivals = verbose
      .filter((other) => other.to === move.to && other.piece === move.piece && other.from !== move.from)
      .map((other) => other.from as unknown as SquareName);

    return {
      san: move.san,
      from: move.from as unknown as SquareName,
      to: move.to as unknown as SquareName,
      type,
      rivals: [...new Set(rivals)],
      // chess.js writes Nbd2 / N1d2 style SAN itself; detecting it by shape
      // rather than re-deriving it keeps chess.js as the single authority.
      isDisambiguated: /^[NBRQK][a-h1-8]x?[a-h][1-8]/.test(move.san),
    };
  });
}

/**
 * Moves where more than one piece of the same type could reach the square.
 * These are the questions that actually train piece selection.
 */
export function contestedMoves(fen: string, type?: PieceType): MoveOption[] {
  return describeMoves(fen).filter(
    (move) => move.rivals.length > 0 && (type === undefined || move.type === type),
  );
}

/** Moves by a given piece type, contested or not. */
export function movesByType(fen: string, type: PieceType): MoveOption[] {
  return describeMoves(fen).filter((move) => move.type === type);
}

/** Total pieces on the board in a FEN, without constructing a Chess instance. */
export function fenPieceCount(fen: string): number {
  const placement = fen.trim().split(/\s+/)[0] ?? '';
  return placement.replace(/[^a-zA-Z]/g, '').length;
}
