#!/usr/bin/env node
/**
 * Regenerates every Android launcher resource from the branding SVGs.
 *
 * Android VectorDrawables are written rather than rasterised PNGs, so this
 * needs no image toolchain and produces resources that stay crisp at any
 * density. That matters here: the machine this was built on has no image
 * library installed, and adding one would make the icon impossible to
 * regenerate on a clean checkout.
 *
 * Outputs:
 *   drawable/ic_launcher_foreground.xml   adaptive foreground
 *   drawable/ic_launcher_monochrome.xml   themed-icon layer (API 33+)
 *   values/ic_launcher_background.xml     adaptive background colour
 *   mipmap-anydpi-v26/ic_launcher.xml     adaptive icon
 *   mipmap-anydpi-v26/ic_launcher_round.xml
 *   drawable/ic_launcher_legacy.xml       pre-API-26 fallback
 *
 * Usage: node scripts/generate-icons.mjs [--check]
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const res = path.join(root, 'android', 'app', 'src', 'main', 'res');
const checkOnly = process.argv.includes('--check');

/** Bight's board colours. Kept here so the icon cannot drift from the app. */
const BOARD_DARK = '#2F4A23';
const BOARD_CREAM = '#EBECD0';

/**
 * The eye lens as a VectorDrawable path.
 *
 * Two cubic arcs meeting at the corners, on the 108dp adaptive canvas. The
 * whole shape sits inside the centre-66dp safe zone so no launcher mask clips
 * it. This is Bight's own geometry - see THIRD_PARTY_NOTICES.md for the
 * inspiration credit.
 */
const LENS = 'M20,54 C32,36 76,36 88,54 C76,72 32,72 20,54 Z';

/** The eight dark squares of the iris checkerboard. */
const CHECKERS = [
  [40.5, 40.5],
  [54, 40.5],
  [47.25, 47.25],
  [60.75, 47.25],
  [40.5, 54],
  [54, 54],
  [47.25, 60.75],
  [60.75, 60.75],
]
  .map(([x, y]) => `M${x},${y} h6.75 v6.75 h-6.75 z`)
  .join(' ');

const foreground = `<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/generate-icons.mjs - do not edit by hand.
    Source: assets/branding/bight-icon-source.svg

    Bight's mark: a cream eye whose iris is a small chessboard. "Bight" means
    board sight, so the mark is a board being looked at.

    108dp adaptive canvas; all artwork inside the centre-66dp safe zone.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- Eye lens -->
    <path
        android:fillColor="${BOARD_CREAM}"
        android:pathData="${LENS}" />

    <!-- Iris: cream disc, then the dark checkers on top -->
    <path
        android:fillColor="${BOARD_CREAM}"
        android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0" />
    <group>
        <clip-path android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0" />
        <path
            android:fillColor="${BOARD_DARK}"
            android:pathData="${CHECKERS}" />
    </group>

    <!-- Iris edge -->
    <path
        android:strokeColor="${BOARD_DARK}"
        android:strokeWidth="3"
        android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0" />

    <!-- Lens outline, drawn last so it sits above both fills -->
    <path
        android:strokeColor="${BOARD_DARK}"
        android:strokeWidth="4.5"
        android:strokeLineJoin="round"
        android:pathData="${LENS}" />
</vector>
`;

const monochrome = `<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/generate-icons.mjs - do not edit by hand.
    Source: assets/branding/bight-icon-monochrome.svg

    Themed-icon layer (API 33+). Android tints this with the system accent and
    ignores colour, so everything is a single fill and the board motif is cut
    out rather than painted, which keeps it legible after tinting.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108"
    android:tint="?android:attr/colorControlNormal">

    <path
        android:fillColor="#FFFFFF"
        android:fillType="evenOdd"
        android:pathData="${LENS} M26,54 C36,41 72,41 82,54 C72,67 36,67 26,54 Z" />

    <path
        android:fillColor="#FFFFFF"
        android:fillType="evenOdd"
        android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0 ${CHECKERS}" />
</vector>
`;

const legacy = `<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/generate-icons.mjs - do not edit by hand.
    Pre-API-26 fallback: the same mark with the background baked in, since
    older launchers have no adaptive-icon layers to compose.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <path android:fillColor="${BOARD_DARK}" android:pathData="M0,0 h108 v108 h-108 z" />
    <path android:fillColor="${BOARD_CREAM}" android:pathData="${LENS}" />
    <path
        android:fillColor="${BOARD_CREAM}"
        android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0" />
    <group>
        <clip-path android:pathData="M54,54 m-13.5,0 a13.5,13.5 0 1,0 27,0 a13.5,13.5 0 1,0 -27,0" />
        <path android:fillColor="${BOARD_DARK}" android:pathData="${CHECKERS}" />
    </group>
    <path
        android:strokeColor="${BOARD_DARK}"
        android:strokeWidth="4.5"
        android:strokeLineJoin="round"
        android:pathData="${LENS}" />
</vector>
`;

const background = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate-icons.mjs - do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">${BOARD_DARK}</color>
</resources>
`;

const adaptive = (round) => `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/generate-icons.mjs - do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
${round ? '' : ''}`;

/*
 * `mipmap-anydpi-v26` serves API 26+ with the adaptive icon; plain
 * `mipmap-anydpi` serves API 22-25 with the flattened vector. Both are needed
 * because Capacitor's minSdk is 22, and deleting the stock PNGs without a
 * fallback would leave older launchers with no icon resource at all.
 */
const outputs = [
  ['drawable/ic_launcher_foreground.xml', foreground],
  ['drawable/ic_launcher_monochrome.xml', monochrome],
  ['drawable/ic_launcher_legacy.xml', legacy],
  ['values/ic_launcher_background.xml', background],
  ['mipmap-anydpi-v26/ic_launcher.xml', adaptive(false)],
  ['mipmap-anydpi-v26/ic_launcher_round.xml', adaptive(true)],
  ['mipmap-anydpi/ic_launcher.xml', legacy],
  ['mipmap-anydpi/ic_launcher_round.xml', legacy],
];

let mismatches = 0;

for (const [relative, contents] of outputs) {
  const target = path.join(res, relative);
  if (checkOnly) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== contents) {
      console.error(`Out of date: ${relative}`);
      mismatches += 1;
    }
    continue;
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, contents);
  console.log(`wrote ${relative}`);
}

if (checkOnly) {
  if (mismatches > 0) {
    console.error(`\n${mismatches} icon resource(s) differ. Run: node scripts/generate-icons.mjs`);
    process.exit(1);
  }
  console.log('Icon resources are up to date.');
}
